/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk_dm using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=processRawResponses_bd815707df
ROOST_METHOD_SIG_HASH=processRawResponses_b550986252

Scenario 1: Process Single Raw Response with Non-Blank Text Chunk (Non-Thought)

Details:
  TestName: processSingleRawResponseWithNonBlankTextChunk
  Description: This test verifies that when a single GenerateContentResponse with a non-blank text chunk (non-thought) is processed, the method correctly accumulates the text and emits a partial LlmResponse with the text content marked as partial.

Execution:
  Arrange: Create a mock GenerateContentResponse with a non-blank text chunk in Part 0. Set up the Part to have thought() return false. Mock GeminiUtil.getPart0FromLlmResponse to return this Part.
  Act: Create a Flowable with the single GenerateContentResponse and pass it to processRawResponses method. Collect the emitted LlmResponse items.
  Assert: Verify that exactly one LlmResponse is emitted. Assert that the emitted response contains the expected text content, has partial flag set to true, and the content role is "model".

Validation:
  This test ensures that the basic streaming functionality works correctly for regular text responses. It validates that text accumulation begins properly and partial responses are emitted as expected. This is critical for real-time streaming scenarios where users expect incremental content delivery.

---

Scenario 2: Process Single Raw Response with Non-Blank Text Chunk (Thought)

Details:
  TestName: processSingleRawResponseWithThoughtTextChunk
  Description: This test validates that when a GenerateContentResponse contains a text chunk marked as a thought, the method correctly accumulates it separately and emits a thinking response marked as partial.

Execution:
  Arrange: Create a mock GenerateContentResponse with a non-blank text chunk. Set up the Part to have thought() return true. Mock GeminiUtil.getPart0FromLlmResponse to return this Part.
  Act: Create a Flowable with the single GenerateContentResponse and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that one LlmResponse is emitted. Assert that the response is created via thinkingResponseFromText, contains the thought text, has partial flag set to true, and the Part has thought flag set to true.

Validation:
  This test confirms that thought content is handled separately from regular text content. It ensures that the system can distinguish between thinking processes and actual responses, which is important for transparency in AI reasoning and for applications that need to display or log the model's reasoning process.

---

Scenario 3: Process Multiple Raw Responses with Consecutive Non-Blank Text Chunks

Details:
  TestName: processMultipleRawResponsesWithConsecutiveTextChunks
  Description: This test checks that multiple consecutive GenerateContentResponse objects with non-blank text chunks are correctly accumulated and each chunk emits a partial response.

Execution:
  Arrange: Create multiple mock GenerateContentResponse objects, each with different non-blank text chunks. All Parts should have thought() return false. Mock GeminiUtil.getPart0FromLlmResponse for each response.
  Act: Create a Flowable with all GenerateContentResponse objects and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that the number of emitted responses matches the number of input responses. Assert that each emitted response contains the corresponding text chunk and has partial flag set to true. Verify that text accumulation works correctly across multiple chunks.

Validation:
  This test validates the streaming accumulation behavior over multiple chunks. It ensures that the method can handle continuous streams of text data without losing information and that each chunk is properly emitted for real-time display. This is essential for maintaining smooth user experience during long-form content generation.

---

Scenario 4: Process Raw Response with Blank Text Chunk and Accumulated Text

Details:
  TestName: processRawResponseWithBlankTextAndAccumulatedText
  Description: This test verifies that when a blank text chunk is received after accumulating text, and GeminiUtil.shouldEmitAccumulatedText returns true, the accumulated text is emitted as a complete response.

Execution:
  Arrange: Create two GenerateContentResponse objects: first with non-blank text, second with blank text. Mock GeminiUtil.getPart0FromLlmResponse accordingly. Mock GeminiUtil.shouldEmitAccumulatedText to return true for the second response.
  Act: Create a Flowable with both responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that two responses are emitted: one partial response for the first chunk, and one complete aggregated response containing the accumulated text. Assert that the aggregated response is not marked as partial.

Validation:
  This test ensures that accumulated text is properly finalized and emitted when a blank chunk signals the end of a text segment. This is important for maintaining proper message boundaries in streaming responses and ensuring that complete thoughts or sentences are delivered as cohesive units.

---

Scenario 5: Process Raw Response with Blank Text Chunk and Accumulated Thought Text

Details:
  TestName: processRawResponseWithBlankTextAndAccumulatedThoughtText
  Description: This test validates that when a blank text chunk is received after accumulating thought text, and shouldEmitAccumulatedText returns true, the accumulated thought text is emitted as a complete thinking response.

Execution:
  Arrange: Create two GenerateContentResponse objects: first with non-blank thought text (thought() returns true), second with blank text. Mock GeminiUtil.getPart0FromLlmResponse and GeminiUtil.shouldEmitAccumulatedText to return true for the second response.
  Act: Create a Flowable with both responses and pass to processRawResponses. Collect emitted LlmResponse items.
  Assert: Verify that two responses are emitted: one partial thinking response for the first chunk, and one complete aggregated thinking response. Assert that the aggregated response has the thought flag set and contains all accumulated thought text.

Validation:
  This test confirms that thought content accumulation and finalization works correctly, separate from regular text. It ensures that thinking processes are properly bounded and delivered as complete units, which is crucial for applications that need to track and display the model's reasoning steps distinctly.

---

Scenario 6: Process Raw Response with Blank Text and No Accumulated Text

Details:
  TestName: processRawResponseWithBlankTextAndNoAccumulatedText
  Description: This test checks that when a blank text chunk is received with no accumulated text, the current processed LlmResponse is emitted without any aggregated text responses.

Execution:
  Arrange: Create a single GenerateContentResponse with blank text. Mock GeminiUtil.getPart0FromLlmResponse to return a Part with empty text. Mock GeminiUtil.shouldEmitAccumulatedText to return false.
  Act: Create a Flowable with the response and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that exactly one response is emitted, which is the current processed LlmResponse created from the raw response. Assert that no additional aggregated text responses are emitted.

Validation:
  This test ensures that the method handles empty chunks gracefully without generating spurious responses. It validates that the system only emits meaningful content and properly passes through metadata or control responses that don't contain text content.

---

Scenario 7: Process Raw Responses Ending with STOP Finish Reason and Accumulated Text

Details:
  TestName: processRawResponsesEndingWithStopAndAccumulatedText
  Description: This test verifies that when the final raw response has a STOP finish reason and there is accumulated text, the accumulated text is emitted as a final complete response.

Execution:
  Arrange: Create two GenerateContentResponse objects: first with non-blank text, second with blank text and a Candidate with finishReason set to STOP. Mock GeminiUtil.getPart0FromLlmResponse for both. Ensure the second response's candidates contain a Candidate with STOP finish reason.
  Act: Create a Flowable with both responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that responses include the partial response from the first chunk and a final complete response containing all accumulated text. Assert that the final response is emitted after the stream completes.

Validation:
  This test ensures that when streaming ends with a STOP signal, any remaining accumulated text is properly finalized and emitted. This is critical for ensuring no content is lost at the end of streaming and that the final response is properly marked as complete.

---

Scenario 8: Process Raw Responses Ending with STOP Finish Reason and Accumulated Thought Text

Details:
  TestName: processRawResponsesEndingWithStopAndAccumulatedThoughtText
  Description: This test validates that when the final raw response has a STOP finish reason and there is accumulated thought text, the accumulated thought text is emitted as a final complete thinking response.

Execution:
  Arrange: Create two GenerateContentResponse objects: first with non-blank thought text (thought() returns true), second with blank text and STOP finish reason. Mock GeminiUtil.getPart0FromLlmResponse and set up the Candidate with STOP finish reason.
  Act: Create a Flowable with both responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that responses include the partial thinking response from the first chunk and a final complete thinking response. Assert that the final thinking response has the thought flag set and contains all accumulated thought text.

Validation:
  This test confirms that thought content is properly finalized when streaming ends with a STOP signal. It ensures that thinking processes are completed and delivered even at the end of the stream, maintaining consistency in how thought content is handled throughout the streaming lifecycle.

---

Scenario 9: Process Raw Responses Ending with STOP and Both Accumulated Text and Thought Text

Details:
  TestName: processRawResponsesEndingWithStopAndBothAccumulatedTexts
  Description: This test checks that when the final response has a STOP finish reason and both accumulated text and thought text exist, both are emitted as separate final responses in the correct order.

Execution:
  Arrange: Create three GenerateContentResponse objects: first with thought text, second with regular text, third with blank text and STOP finish reason. Mock GeminiUtil.getPart0FromLlmResponse for all responses.
  Act: Create a Flowable with all responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that the emitted responses include partial responses for both chunks and two final complete responses: one thinking response and one regular text response. Assert that the thinking response is emitted before the text response.

Validation:
  This test validates that the method can handle mixed content types and properly finalize both thought and regular text when streaming ends. It ensures that the order of finalization is correct and that both content types are preserved and delivered completely.

---

Scenario 10: Process Raw Responses Ending with Non-STOP Finish Reason

Details:
  TestName: processRawResponsesEndingWithNonStopFinishReason
  Description: This test verifies that when the final raw response has a finish reason other than STOP, no additional final responses are emitted even if there is accumulated text.

Execution:
  Arrange: Create two GenerateContentResponse objects: first with non-blank text, second with blank text and a Candidate with finishReason set to something other than STOP (e.g., MAX_TOKENS). Mock GeminiUtil.getPart0FromLlmResponse accordingly.
  Act: Create a Flowable with both responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that only the partial response from the first chunk is emitted. Assert that no final aggregated response is emitted despite having accumulated text.

Validation:
  This test ensures that the method respects different finish reasons and only finalizes content when appropriate. It validates that incomplete or interrupted streams are handled correctly without forcing premature finalization, which is important for error handling and stream interruption scenarios.

---

Scenario 11: Process Empty Flowable of Raw Responses

Details:
  TestName: processEmptyFlowableOfRawResponses
  Description: This test checks that when an empty Flowable is passed to processRawResponses, no responses are emitted and the method completes without errors.

Execution:
  Arrange: Create an empty Flowable of GenerateContentResponse.
  Act: Pass the empty Flowable to processRawResponses and collect all emitted items.
  Assert: Verify that no LlmResponse items are emitted. Assert that the Flowable completes successfully without throwing any exceptions.

Validation:
  This test validates the method's robustness in handling edge cases where no data is provided. It ensures that the method can gracefully handle empty streams without crashing or producing unexpected output, which is important for reliability in various streaming scenarios.

---

Scenario 12: Process Raw Response with Null Last Raw Response Holder

Details:
  TestName: processRawResponseWithNullLastRawResponseHolder
  Description: This test verifies that when the deferred final emission logic runs but the lastRawResponseHolder is null, an empty Flowable is returned without errors.

Execution:
  Arrange: Create an empty Flowable of GenerateContentResponse to ensure lastRawResponseHolder remains null.
  Act: Invoke processRawResponses with the empty Flowable and collect all emitted items.
  Assert: Verify that no items are emitted and the stream completes successfully. Assert that no NullPointerException or other exceptions are thrown.

Validation:
  This test ensures that the method handles the case where no responses have been processed before the final deferred emission. It validates null-safety and proper initialization of the lastRawResponseHolder, which is critical for preventing runtime errors in edge cases.

---

Scenario 13: Process Raw Responses with shouldEmitAccumulatedText Returning False

Details:
  TestName: processRawResponsesWithShouldEmitAccumulatedTextFalse
  Description: This test validates that when a blank text chunk is received with accumulated text but GeminiUtil.shouldEmitAccumulatedText returns false, the accumulated text is not emitted as an aggregated response.

Execution:
  Arrange: Create two GenerateContentResponse objects: first with non-blank text, second with blank text. Mock GeminiUtil.getPart0FromLlmResponse for both. Mock GeminiUtil.shouldEmitAccumulatedText to return false for the second response.
  Act: Create a Flowable with both responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that only the partial response from the first chunk is emitted. Assert that no aggregated text response is emitted and the current processed response is emitted instead.

Validation:
  This test confirms that the method respects the shouldEmitAccumulatedText condition and doesn't prematurely emit accumulated text. It ensures that text accumulation continues when appropriate, which is important for maintaining proper message boundaries based on the response structure.

---

Scenario 14: Process Raw Responses with Mixed Thought and Non-Thought Text Chunks

Details:
  TestName: processRawResponsesWithMixedThoughtAndNonThoughtChunks
  Description: This test checks that when processing a sequence of responses with alternating thought and non-thought text chunks, each type is accumulated separately and emitted correctly.

Execution:
  Arrange: Create four GenerateContentResponse objects alternating between thought text (thought() returns true) and regular text (thought() returns false). Mock GeminiUtil.getPart0FromLlmResponse for all responses.
  Act: Create a Flowable with all responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that four partial responses are emitted, alternating between thinking responses and regular text responses. Assert that each response contains the correct text and thought flag.

Validation:
  This test validates that the method can handle interleaved thought and regular text content, maintaining separate accumulation for each type. It ensures that the system can track multiple content streams simultaneously, which is important for complex AI responses that mix reasoning and output.

---

Scenario 15: Process Raw Responses with Part Containing No Text

Details:
  TestName: processRawResponsesWithPartContainingNoText
  Description: This test verifies that when a Part is present but contains no text (text() returns empty Optional), the method treats it as a blank text chunk.

Execution:
  Arrange: Create a GenerateContentResponse with a Part where text() returns Optional.empty(). Mock GeminiUtil.getPart0FromLlmResponse to return this Part.
  Act: Create a Flowable with the response and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that the current processed LlmResponse is emitted without any text content. Assert that no partial text responses are generated.

Validation:
  This test ensures that the method handles Parts without text content correctly, treating them as control or metadata responses. It validates that the absence of text is properly detected and handled, which is important for processing various types of streaming responses beyond just text.

---

Scenario 16: Process Raw Responses with Whitespace-Only Text Chunk

Details:
  TestName: processRawResponsesWithWhitespaceOnlyTextChunk
  Description: This test checks that when a text chunk contains only whitespace characters, it is treated as blank and no partial text response is emitted.

Execution:
  Arrange: Create a GenerateContentResponse with a Part containing only whitespace (e.g., "   " or "\n\t"). Mock GeminiUtil.getPart0FromLlmResponse to return this Part.
  Act: Create a Flowable with the response and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that no partial text response is emitted for the whitespace chunk. Assert that the current processed LlmResponse is emitted instead.

Validation:
  This test validates that the method uses isBlank() correctly to filter out whitespace-only content. It ensures that meaningless whitespace doesn't generate spurious responses, which is important for maintaining clean output and avoiding unnecessary processing.

---

Scenario 17: Process Raw Responses with Candidates Empty Optional

Details:
  TestName: processRawResponsesWithCandidatesEmptyOptional
  Description: This test verifies that when the final GenerateContentResponse has an empty candidates Optional, the finish reason check defaults to false and no final responses are emitted.

Execution:
  Arrange: Create a GenerateContentResponse with candidates() returning Optional.empty(). Ensure there is some accumulated text from a previous response.
  Act: Create a Flowable with the responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that only the partial response from the text chunk is emitted. Assert that no final aggregated response is emitted because the finish reason check returns false.

Validation:
  This test ensures that the method handles missing candidates gracefully and doesn't assume a STOP finish reason. It validates that the finish reason logic is robust and handles Optional values correctly, which is important for processing various response formats.

---

Scenario 18: Process Raw Responses with Empty Candidates List

Details:
  TestName: processRawResponsesWithEmptyCandidatesList
  Description: This test checks that when the candidates Optional contains an empty list, the finish reason check defaults to false and no final responses are emitted.

Execution:
  Arrange: Create a GenerateContentResponse with candidates() returning Optional of an empty list. Include a previous response with accumulated text.
  Act: Create a Flowable with the responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that only the partial response is emitted. Assert that no final aggregated response is emitted due to the empty candidates list.

Validation:
  This test validates that the method handles empty candidates lists correctly without throwing exceptions. It ensures that the stream() and findFirst() operations work properly with empty collections, which is important for robustness in handling various API response formats.

---

Scenario 19: Process Raw Responses with Candidate Missing Finish Reason

Details:
  TestName: processRawResponsesWithCandidateMissingFinishReason
  Description: This test verifies that when a Candidate exists but has no finish reason (finishReason() returns empty Optional), the finish reason check defaults to false.

Execution:
  Arrange: Create a GenerateContentResponse with a Candidate where finishReason() returns Optional.empty(). Include accumulated text from a previous response.
  Act: Create a Flowable with the responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that only the partial response is emitted. Assert that no final aggregated response is emitted because the finish reason is absent.

Validation:
  This test ensures that the method handles missing finish reasons gracefully without assuming a default value. It validates that the Optional chaining works correctly and that the method doesn't emit final responses prematurely, which is important for correct stream termination handling.

---

Scenario 20: Process Raw Responses with Multiple Candidates (First Has STOP)

Details:
  TestName: processRawResponsesWithMultipleCandidatesFirstHasStop
  Description: This test checks that when multiple candidates exist and the first one has a STOP finish reason, the accumulated text is emitted as a final response.

Execution:
  Arrange: Create a GenerateContentResponse with multiple Candidates, where the first has finishReason STOP and others have different finish reasons. Include accumulated text from a previous response.
  Act: Create a Flowable with the responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that the partial response and a final aggregated response are emitted. Assert that the finish reason check uses the first candidate's STOP reason.

Validation:
  This test validates that the method correctly uses findFirst() to select the first candidate when multiple exist. It ensures that the finish reason logic works correctly with multiple candidates, which is important for handling complex API responses with multiple generation alternatives.

---

Scenario 21: Process Large Number of Consecutive Text Chunks

Details:
  TestName: processLargeNumberOfConsecutiveTextChunks
  Description: This test verifies that the method can handle a large number of consecutive text chunks without performance degradation or memory issues.

Execution:
  Arrange: Create 1000 GenerateContentResponse objects, each with a small non-blank text chunk. Mock GeminiUtil.getPart0FromLlmResponse for all responses.
  Act: Create a Flowable with all 1000 responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that 1000 partial responses are emitted, one for each chunk. Assert that the text accumulation works correctly across all chunks without loss.

Validation:
  This test ensures that the method can handle high-volume streaming scenarios without performance issues. It validates that the StringBuilder accumulation is efficient and that the method scales well with large numbers of chunks, which is critical for long-form content generation.

---

Scenario 22: Process Raw Responses with Accumulated Text Exceeding StringBuilder Capacity

Details:
  TestName: processRawResponsesWithLargeAccumulatedText
  Description: This test checks that the method can handle very large accumulated text that exceeds the default StringBuilder capacity without errors.

Execution:
  Arrange: Create multiple GenerateContentResponse objects with large text chunks that together exceed 16KB (default StringBuilder capacity). Mock GeminiUtil.getPart0FromLlmResponse for all responses. Add a final response with blank text and STOP finish reason.
  Act: Create a Flowable with all responses and invoke processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that all partial responses are emitted correctly. Assert that the final aggregated response contains all accumulated text without truncation or corruption.

Validation:
  This test validates that the StringBuilder can dynamically grow to accommodate large amounts of text. It ensures that there are no buffer overflow issues or text loss when processing very long responses, which is important for handling extensive content generation.

---

Scenario 23: Process Raw Responses with Concurrent Thought and Text Accumulation

Details:
  TestName: processRawResponsesWithConcurrentThoughtAndTextAccumulation
  Description: This test verifies that when thought text and regular text are accumulated concurrently and then both encounter blank chunks with shouldEmitAccumulatedText returning true, both are emitted correctly.

Execution:
  Arrange: Create four GenerateContentResponse objects: first with thought text, second with regular text, third with blank text where shouldEmitAccumulatedText returns true for both accumulators. Mock GeminiUtil.getPart0FromLlmResponse and GeminiUtil.shouldEmitAccumulatedText accordingly.
  Act: Create a Flowable with all responses and pass to processRawResponses. Collect all emitted LlmResponse items.
  Assert: Verify that partial responses for both thought and text are emitted, followed by aggregated responses for both when the blank chunk is processed. Assert that both accumulators are cleared after emission.

Validation:
  This test ensures that the method can manage multiple accumulation buffers simultaneously and emit them independently when appropriate. It validates that the separate tracking of thought and regular text works correctly, which is important for complex streaming scenarios with mixed content types.

---

Scenario 24: Process Raw Responses with Part.get() on Empty Optional

Details:
  TestName: processRawResponsesWithPartGetOnEmptyOptional
  Description: This test checks the behavior when GeminiUtil.getPart0FromLlmResponse returns an empty Optional and the code attempts to call get() on it.

Execution:
  Arrange: Create a GenerateContentResponse where GeminiUtil.getPart0FromLlmResponse returns Optional.empty(). This simulates a response without any parts.
  Act: Create a Flowable with the response and invoke processRawResponses. Attempt to collect emitted items.
  Assert: Verify that a NoSuchElementException is thrown when part.get() is called on an empty Optional, or verify that the code handles this case gracefully if there's defensive programming.

Validation:
  This test identifies a potential bug in the code where part.get() is called without checking if the Optional is present. It validates error handling for malformed responses and ensures that the method either handles missing parts gracefully or fails predictably, which is important for debugging and error reporting.

---

Scenario 25: Process Raw Responses Logging Behavior

Details:
  TestName: processRawResponsesLoggingBehavior
  Description: This test verifies that appropriate log messages are generated at TRACE and DEBUG levels during response processing.

Execution:
  Arrange: Set up a log capture mechanism for the logger. Create several GenerateContentResponse objects with various content types. Mock GeminiUtil.getPart0FromLlmResponse for all responses.
  Act: Create a Flowable with the responses and pass to processRawResponses. Collect all emitted items.
  Assert: Verify that TRACE level logs are generated for each raw streaming response. Assert that DEBUG level logs are generated for responses to emit. Verify that log messages contain expected information about the responses.

Validation:
  This test ensures that the logging functionality works correctly and provides useful debugging information. It validates that the appropriate log levels are used and that log messages contain relevant data, which is important for troubleshooting and monitoring streaming operations in production.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import com.google.genai.types.Candidate;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Flowable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;

class GeminiProcessRawResponsesTest {

  @BeforeEach
  void setUp() {
    // Setup common test fixtures if needed
  }

  @Test
  @Tag("valid")
  void processSingleRawResponseWithNonBlankTextContent() {
    String textContent = "Hello World";
    Part mockPart = mock(Part.class);
    when(mockPart.text()).thenReturn(Optional.of(textContent));
    when(mockPart.thought()).thenReturn(Optional.of(false));
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);
    LlmResponse partialResponse = createMockLlmResponseWithBuilder();

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processMultipleRawResponsesWithAccumulatedText() {
    String text1 = "Hello";
    String text2 = " World";
    String text3 = "!";
    Part mockPart1 = createMockPart(text1, false);
    Part mockPart2 = createMockPart(text2, false);
    Part mockPart3 = createMockPart(text3, false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(3, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponseWithThoughtContent() {
    String thoughtText = "Thinking...";
    Part mockPart = createMockPart(thoughtText, true);
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithBlankTextContent() {
    Part mockPart = createMockPart("   ", false);
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse))
          .thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponseTriggeringAccumulatedTextEmission() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse2))
          .thenReturn(true);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 2);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponseTriggeringAccumulatedThoughtTextEmission() {
    Part mockPart1 = createMockPart("Thinking...", true);
    Part mockPart2 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse2))
          .thenReturn(true);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 2);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithFinalStopFinishReasonAndAccumulatedText() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 =
        createMockResponseWithFinishReason(FinishReason.Known.STOP);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 2);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithFinalStopFinishReasonAndAccumulatedThoughtText() {
    Part mockPart1 = createMockPart("Thinking...", true);
    Part mockPart2 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 =
        createMockResponseWithFinishReason(FinishReason.Known.STOP);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 2);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithFinalStopFinishReasonAndBothAccumulatedTextTypes() {
    Part mockPart1 = createMockPart("Thinking...", true);
    Part mockPart2 = createMockPart("Hello", false);
    Part mockPart3 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 =
        createMockResponseWithFinishReason(FinishReason.Known.STOP);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 3);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithNonStopFinishReason() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 =
        createMockResponseWithFinishReason(FinishReason.Known.MAX_TOKENS);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(2, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processEmptyFlowableOfRawResponses() {
    Flowable<GenerateContentResponse> rawResponses = Flowable.empty();
    List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

    assertNotNull(results);
    assertTrue(results.isEmpty());
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithNoPartAvailable() {
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.empty());
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithPartContainingNoText() {
    Part mockPart = mock(Part.class);
    when(mockPart.text()).thenReturn(Optional.empty());
    when(mockPart.thought()).thenReturn(Optional.of(false));
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithAlternatingThoughtAndRegularText() {
    Part mockPart1 = createMockPart("Thinking...", true);
    Part mockPart2 = createMockPart("Hello", false);
    Part mockPart3 = createMockPart("More thinking", true);
    Part mockPart4 = createMockPart("World", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse4 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse4 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse4)).thenReturn(mockLlmResponse4);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse4))
          .thenReturn(Optional.of(mockPart4));

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3, mockResponse4);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(4, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithNullFinishReason() {
    Part mockPart = createMockPart("", false);
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    when(mockResponse.candidates()).thenReturn(Optional.empty());
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithEmptyCandidatesList() {
    Part mockPart = createMockPart("", false);
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    when(mockResponse.candidates()).thenReturn(Optional.of(Collections.emptyList()));
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithNoCandidatesOptional() {
    Part mockPart = createMockPart("", false);
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    when(mockResponse.candidates()).thenReturn(Optional.empty());
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithMultipleEmissionsBeforeStop() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    Part mockPart3 = createMockPart("World", false);
    Part mockPart4 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse4 =
        createMockResponseWithFinishReason(FinishReason.Known.STOP);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse4 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse4)).thenReturn(mockLlmResponse4);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse4))
          .thenReturn(Optional.of(mockPart4));
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse2))
          .thenReturn(true);
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse4))
          .thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3, mockResponse4);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 4);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponseWithThoughtFlagFalseExplicitly() {
    Part mockPart = mock(Part.class);
    when(mockPart.text()).thenReturn(Optional.of("Hello"));
    when(mockPart.thought()).thenReturn(Optional.of(false));
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponseWithThoughtFlagAbsent() {
    Part mockPart = mock(Part.class);
    when(mockPart.text()).thenReturn(Optional.of("Hello"));
    when(mockPart.thought()).thenReturn(Optional.empty());
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processLargeNumberOfRawResponses() {
    List<GenerateContentResponse> responses = new ArrayList<>();
    List<Part> parts = new ArrayList<>();
    List<LlmResponse> llmResponses = new ArrayList<>();

    for (int i = 0; i < 1000; i++) {
      Part mockPart = createMockPart("Chunk" + i, false);
      parts.add(mockPart);
      GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
      responses.add(mockResponse);
      LlmResponse mockLlmResponse = mock(LlmResponse.class);
      llmResponses.add(mockLlmResponse);
    }

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      for (int i = 0; i < 1000; i++) {
        int index = i;
        llmResponseMock
            .when(() -> LlmResponse.create(responses.get(index)))
            .thenReturn(llmResponses.get(index));
        geminiUtilMock
            .when(() -> GeminiUtil.getPart0FromLlmResponse(llmResponses.get(index)))
            .thenReturn(Optional.of(parts.get(index)));
      }

      Flowable<GenerateContentResponse> rawResponses = Flowable.fromIterable(responses);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1000, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponsesWithOnlyBlankTextChunks() {
    Part mockPart1 = createMockPart("   ", false);
    Part mockPart2 = createMockPart("", false);
    Part mockPart3 = createMockPart("\t\n", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(3, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithMixedBlankAndNonBlankText() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    Part mockPart3 = createMockPart("World", false);
    Part mockPart4 = createMockPart("   ", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse4 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse4 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse4)).thenReturn(mockLlmResponse4);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse4))
          .thenReturn(Optional.of(mockPart4));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3, mockResponse4);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 2);
    }
  }

  @Test
  @Tag("valid")
  void processRawResponseTriggeringBothTextAndThoughtEmissionSimultaneously() {
    Part mockPart1 = createMockPart("Thinking...", true);
    Part mockPart2 = createMockPart("Hello", false);
    Part mockPart3 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse3))
          .thenReturn(true);

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 4);
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponsesWithNullLastResponseHolder() {
    Flowable<GenerateContentResponse> rawResponses = Flowable.empty();
    List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

    assertNotNull(results);
    assertTrue(results.isEmpty());
  }

  @Test
  @Tag("boundary")
  void processRawResponseWithStopFinishReasonButNoAccumulatedText() {
    Part mockPart = createMockPart("", false);
    GenerateContentResponse mockResponse =
        createMockResponseWithFinishReason(FinishReason.Known.STOP);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenReturn(Optional.of(mockPart));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(1, results.size());
    }
  }

  @Test
  @Tag("boundary")
  void processRawResponsesWithWhitespaceOnlyText() {
    Part mockPart1 = createMockPart("   ", false);
    Part mockPart2 = createMockPart("\t\n", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(2, results.size());
    }
  }

  @Test
  @Tag("invalid")
  void processRawResponseWithExceptionDuringPartExtraction() {
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    LlmResponse mockLlmResponse = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse)).thenReturn(mockLlmResponse);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse))
          .thenThrow(new RuntimeException("Part extraction failed"));

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
      assertThrows(
          RuntimeException.class,
          () -> {
            Gemini.processRawResponses(rawResponses).blockingSubscribe();
          });
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithFinishReasonOtherThanStopKnownEnum() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 =
        createMockResponseWithFinishReason(FinishReason.Known.SAFETY);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse1, mockResponse2);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertEquals(2, results.size());
    }
  }

  @Test
  @Tag("valid")
  void processRawResponsesWithConcurrentAccumulationAndEmission() {
    Part mockPart1 = createMockPart("Hello", false);
    Part mockPart2 = createMockPart("", false);
    Part mockPart3 = createMockPart("World", false);
    GenerateContentResponse mockResponse1 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse2 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse3 = mock(GenerateContentResponse.class);
    GenerateContentResponse mockResponse4 =
        createMockResponseWithFinishReason(FinishReason.Known.STOP);
    LlmResponse mockLlmResponse1 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse2 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse3 = mock(LlmResponse.class);
    LlmResponse mockLlmResponse4 = mock(LlmResponse.class);

    try (MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
        MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      llmResponseMock.when(() -> LlmResponse.create(mockResponse1)).thenReturn(mockLlmResponse1);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse2)).thenReturn(mockLlmResponse2);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse3)).thenReturn(mockLlmResponse3);
      llmResponseMock.when(() -> LlmResponse.create(mockResponse4)).thenReturn(mockLlmResponse4);
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse1))
          .thenReturn(Optional.of(mockPart1));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse2))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse3))
          .thenReturn(Optional.of(mockPart3));
      geminiUtilMock
          .when(() -> GeminiUtil.getPart0FromLlmResponse(mockLlmResponse4))
          .thenReturn(Optional.of(mockPart2));
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse2))
          .thenReturn(true);
      geminiUtilMock
          .when(() -> GeminiUtil.shouldEmitAccumulatedText(mockLlmResponse4))
          .thenReturn(false);

      Flowable<GenerateContentResponse> rawResponses =
          Flowable.just(mockResponse1, mockResponse2, mockResponse3, mockResponse4);
      List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();

      assertNotNull(results);
      assertTrue(results.size() >= 4);
    }
  }

  private Part createMockPart(String text, boolean isThought) {
    Part mockPart = mock(Part.class);
    when(mockPart.text()).thenReturn(Optional.of(text));
    when(mockPart.thought()).thenReturn(Optional.of(isThought));
    return mockPart;
  }

  private GenerateContentResponse createMockResponseWithFinishReason(
      FinishReason.Known finishReasonKnown) {
    GenerateContentResponse mockResponse = mock(GenerateContentResponse.class);
    Candidate mockCandidate = mock(Candidate.class);
    FinishReason mockFinishReason = mock(FinishReason.class);
    when(mockFinishReason.knownEnum()).thenReturn(finishReasonKnown);
    when(mockCandidate.finishReason()).thenReturn(Optional.of(mockFinishReason));
    when(mockResponse.candidates()).thenReturn(Optional.of(List.of(mockCandidate)));
    return mockResponse;
  }

  private LlmResponse createMockLlmResponseWithBuilder() {
    LlmResponse mockResponse = mock(LlmResponse.class);
    LlmResponse.Builder mockBuilder = mock(LlmResponse.Builder.class);
    when(mockResponse.toBuilder()).thenReturn(mockBuilder);
    when(mockBuilder.partial(true)).thenReturn(mockBuilder);
    when(mockBuilder.build()).thenReturn(mockResponse);
    return mockResponse;
  }
}
